spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./build/h2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

error-messages:
  employee-has-a-booking: "Employee already has a booking!"
  desk-is-already-booked: "Desk already booked!"
  branch-mismatch: "Branch mismatch!"
  premium-desk-booking: "Only managers can book premium desks!"
  unexpected: "Unexpected error!"
  missing-date: "Date is missing!"
  date-before-today: "Date before today!"
  missing-first-name: "First name is missing!"
  missing-last-name: "Last name is missing!"

server:
  port : 8080
